-- MySQL Script generated by MySQL Workbench
-- Fri Apr  9 18:39:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema spotify
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `spotify` ;

-- -----------------------------------------------------
-- Schema spotify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spotify` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `spotify` ;

-- -----------------------------------------------------
-- Table `spotify`.`artista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`artista` ;

CREATE TABLE IF NOT EXISTS `spotify`.`artista` (
  `id_artista` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `foto_artista` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_artista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`discografia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`discografia` ;

CREATE TABLE IF NOT EXISTS `spotify`.`discografia` (
  `id_discografia` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `pais` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_discografia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`albumes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`albumes` ;

CREATE TABLE IF NOT EXISTS `spotify`.`albumes` (
  `id_albumes` INT NOT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `año_publicacion` DATE NULL DEFAULT NULL,
  `imagen_portada` VARCHAR(100) NULL DEFAULT NULL,
  `id_artista` INT NULL DEFAULT NULL,
  `id_discografia` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_albumes`),
  INDEX `id_artista_idx` (`id_artista` ASC) VISIBLE,
  INDEX `id_disco_albumes_idx` (`id_discografia` ASC) VISIBLE,
  CONSTRAINT `id_artista`
    FOREIGN KEY (`id_artista`)
    REFERENCES `spotify`.`artista` (`id_artista`),
  CONSTRAINT `id_disco_albumes`
    FOREIGN KEY (`id_discografia`)
    REFERENCES `spotify`.`discografia` (`id_discografia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`canciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`canciones` ;

CREATE TABLE IF NOT EXISTS `spotify`.`canciones` (
  `id_canciones` INT NOT NULL,
  `duracion` INT NULL DEFAULT NULL,
  `reproducciones` INT NULL DEFAULT NULL,
  `genero` VARCHAR(45) NULL DEFAULT NULL,
  `likes` INT NULL DEFAULT NULL,
  `id_albumes` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_canciones`),
  INDEX `id_almbumes_canciones_idx` (`id_albumes` ASC) VISIBLE,
  CONSTRAINT `id_almbumes_canciones`
    FOREIGN KEY (`id_albumes`)
    REFERENCES `spotify`.`albumes` (`id_albumes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`generos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`generos` ;

CREATE TABLE IF NOT EXISTS `spotify`.`generos` (
  `id_generos` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_generos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`canciones_generos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`canciones_generos` ;

CREATE TABLE IF NOT EXISTS `spotify`.`canciones_generos` (
  `idcanciones_generos` INT NOT NULL,
  `id_canciones` INT NOT NULL,
  `id_generos` INT NOT NULL,
  PRIMARY KEY (`idcanciones_generos`),
  INDEX `id_canciones_m_idx` (`id_canciones` ASC) VISIBLE,
  INDEX `id_generos_m_idx` (`id_generos` ASC) VISIBLE,
  CONSTRAINT `id_canciones_m`
    FOREIGN KEY (`id_canciones`)
    REFERENCES `spotify`.`canciones` (`id_canciones`),
  CONSTRAINT `id_generos_m`
    FOREIGN KEY (`id_generos`)
    REFERENCES `spotify`.`generos` (`id_generos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`usuario` ;

CREATE TABLE IF NOT EXISTS `spotify`.`usuario` (
  `id_usuario` INT NOT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `genero` VARCHAR(40) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(10) NULL DEFAULT NULL,
  `pais` VARCHAR(100) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`password`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`password` ;

CREATE TABLE IF NOT EXISTS `spotify`.`password` (
  `idpassword` INT NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `fecha_modificacion` DATETIME NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`idpassword`),
  INDEX `id_usuario_pass_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `id_usuario_pass`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `spotify`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`playlist` ;

CREATE TABLE IF NOT EXISTS `spotify`.`playlist` (
  `id_playlist` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `numero_canciones` INT NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `estado` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `fecha_eliminacion` DATETIME NOT NULL,
  PRIMARY KEY (`id_playlist`),
  INDEX `id_usuarios_playlist_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `id_usuarios_playlist`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `spotify`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`playlist_canciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`playlist_canciones` ;

CREATE TABLE IF NOT EXISTS `spotify`.`playlist_canciones` (
  `id_playlist_canciones` INT NOT NULL,
  `id_canciones` INT NOT NULL,
  `id_playlist` INT NOT NULL,
  PRIMARY KEY (`id_playlist_canciones`),
  INDEX `id_canciones_playlist_idx` (`id_canciones` ASC) VISIBLE,
  INDEX `id_playlist_canciones_idx` (`id_playlist` ASC) VISIBLE,
  CONSTRAINT `id_canciones_playlist`
    FOREIGN KEY (`id_canciones`)
    REFERENCES `spotify`.`canciones` (`id_canciones`),
  CONSTRAINT `id_playlist_canciones`
    FOREIGN KEY (`id_playlist`)
    REFERENCES `spotify`.`playlist` (`id_playlist`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`suscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`suscripcion` ;

CREATE TABLE IF NOT EXISTS `spotify`.`suscripcion` (
  `id_suscripcion` INT NOT NULL,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_renovacion` DATETIME NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_suscripcion`),
  INDEX `id_usuario_sus_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `id_usuario_sus`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `spotify`.`usuario` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`registro_pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`registro_pagos` ;

CREATE TABLE IF NOT EXISTS `spotify`.`registro_pagos` (
  `id_registro_pagos` INT NOT NULL,
  `pagos` VARCHAR(45) NOT NULL,
  `fecha_pagos` VARCHAR(45) NOT NULL,
  `id_suscripcion` INT NOT NULL,
  PRIMARY KEY (`id_registro_pagos`),
  INDEX `id_suscripcion_regis_idx` (`id_suscripcion` ASC) VISIBLE,
  CONSTRAINT `id_suscripcion_regis`
    FOREIGN KEY (`id_suscripcion`)
    REFERENCES `spotify`.`suscripcion` (`id_suscripcion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`tarjeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`tarjeta` ;

CREATE TABLE IF NOT EXISTS `spotify`.`tarjeta` (
  `id_tarjeta` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `ultimos_digitos` VARCHAR(4) NOT NULL,
  `fecha_vencimiento` DATE NOT NULL,
  `id_resgistro_pago` INT NOT NULL,
  PRIMARY KEY (`id_tarjeta`),
  INDEX `id_resgistro_pago_tarjeta_idx` (`id_resgistro_pago` ASC) VISIBLE,
  CONSTRAINT `id_resgistro_pago_tarjeta`
    FOREIGN KEY (`id_resgistro_pago`)
    REFERENCES `spotify`.`registro_pagos` (`id_registro_pagos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `spotify`.`transferencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify`.`transferencia` ;

CREATE TABLE IF NOT EXISTS `spotify`.`transferencia` (
  `id_transferencia` INT NOT NULL,
  `CBU` VARCHAR(45) NULL DEFAULT NULL,
  `alias` VARCHAR(45) NULL DEFAULT NULL,
  `id_resgistro_pago` INT NOT NULL,
  PRIMARY KEY (`id_transferencia`),
  INDEX `id_resgistro_pago_trans_idx` (`id_resgistro_pago` ASC) VISIBLE,
  CONSTRAINT `id_resgistro_pago_trans`
    FOREIGN KEY (`id_resgistro_pago`)
    REFERENCES `spotify`.`registro_pagos` (`id_registro_pagos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `spotify`.`artista`
(`id_artista`,
`nombre`,
`foto_artista`)
VALUES
('1','AC/DC','AQUI VA LA FOTO DE LA BANDA'),
('2','Accept','AQUI VA LA FOTO DE LA BANDA'),
('3','Aerosmith','AQUI VA LA FOTO DE LA BANDA');

INSERT INTO `spotify`.`usuario`
(`id_usuario`,
`fecha_nacimiento`,
`genero`,
`codigo_postal`,
`pais`,
`nombre`,
`email`)
VALUES
('1','1993-07-01','masculino','12345','Argentina','Juanito','juanito@correo.com'),
('2','1995-07-01','femenino','54321','Peru','Juana','juana@correo.com'),
('3','1999-07-01','femenino','ss528','USA','Paola','Paola@correo.com');

INSERT INTO `spotify`.`albumes`
(`id_albumes`,
`titulo`,
`id_artista`)
VALUES
('1','For Those About To Rock We Salute You','1'),
('2','Restless and Wild','2'),
('3','Let There Be Rock','2');

INSERT INTO `spotify`.`canciones`
(`id_canciones`,
`duracion`,
`id_albumes`)
VALUES
('1','343719','1'),
('2','252051','2'),
('3','343719','2');




